### ISSUE TITLE
Image width issue with maps

### ISSUE THREAD

**Issue by kennethlove** [dhg/Skeleton#10]
At least with the Leaflet.js map library, the `img { max-width: 100% }` rule makes images not load at all in Firefox. This might affect other map libraries (YMaps, Google Maps, etc) but I haven't tested those.

**Comment by dhg** [comment]
Hey Kenneth, 

Good call. I actually noticed it messed with some jQuery slider plugins too, so I've commented out the declaration with clear notes about why it was there and how it can still be used on specific images rather than every image on a site :) It was honestly a poor declaration (much better to target images that you want to size with the grid). 

Appreciate your contribution and look forward to seeing what you make with Skeleton (please let me know!)

Cheers
