### ISSUE TITLE
<code> formatting

### ISSUE THREAD

**Issue by honza** [dhg/Skeleton#13]
Is there a plan for some programming-friendly formatting for the `<code>` and `<pre>` tags? Thanks

**Comment by dhg** [comment]
Hi Honza, 

Honestly, I don't think so. It's not something that I frequently use and if I do, I often leverage a plugin or embed service because the raw '<code>` often becomes to unmanageable. I'll actually check it out a bit and see if there's anything really low touch I can do, but I don't think it will make it in a release. If you have some killer reason it should be included though, please let me know!

**Comment by honza** [comment]
Thanks, man. I was just wondering if that was something you had in mind. No worries!
