### ISSUE TITLE
invalid CSS

### ISSUE THREAD

**Issue by johnnysky** [dhg/Skeleton#132]
I notice that the latest version of Skeleton has several CSS validation errors. Any chance that these will be fixed in a future version?

**Comment by dhg** [comment]
I hope these are fixed now! Question for you - what validator were you running it through?

**Comment by dhg** [comment]
Just ran it through a couple validators and everything seems to be looking good now, so hopefully this isn't an issue anymore, but please re-open if it's something that persists!

**Comment by johnnysky** [comment]
Hi Dave,

Thanks for your message. I use the standard W3C CSS validator at:
The W3C CSS Validation Service http://jigsaw.w3.org/css-validator/

I just downloaded the current Skeleton, and ran it through the W3C’s CSS Validator. 

Unfortunately, there is still one validation error, according to the W3C.

For the “skeleton.css” file it lists one error for line 226:
Property appearance doesn't exist : none

I poked around, and found a post on a css-tricks.com http://css-tricks.com/ forum where someone said:
Looks like appearance property has been dropped from spec1 http://wiki.csswg.org/spec/css4-ui#dropped-css3-features.

I guess the “appearance" property was in an earlier CSS spec, but was dropped. That’s all I know right now.

Perhaps I’ll post this again in the GitHub forum, if you think it would help.

Cheers!
John

**Comment by dhg** [comment]
Gotcha - great to know. I'll dig into the validity of the appearance property. It's something I've used for a while now and had no idea it was deprecated. Let me dig further. Thanks for pointing this out man.

**Comment by dhg** [comment]
Okay, so I checked into this. While `appearance` may be getting a deprecation or some modification, it is still implemented and has functionality in a number of browsers (including Safari for iOS). I really wish it would validate, but in this specific case it's something important to the styling of form elements in Skeleton, whether or not it validates :(

I'm not sure what the best way to solve your issue is, but if it's between W3C validated CSS and optimal presentation on all devices, I'm going to have to choose to latter. Hope that seems agreeable. 

I'm going to close the issue for now, but I'm more than happy to chat more in the comments and re-open if you have a proposed solution!

Thanks again for taking the time @johnnysky and let me know.
