### ISSUE TITLE
Disabled buttons

### ISSUE THREAD

**Issue by jamesfairhurst** [dhg/Skeleton#14]
Great boiler plate, been using it for a personal project and needed some disabled submit buttons, may be useful to include some in your CSS. A really basic style I've used:

```
button[disabled] {
    background:#ccc;
    border-color: #ccc;
    text-shadow:none;
}
```

**Comment by dhg** [comment]
Hey James, 

Thanks for the simple CSS addition. I spent some noodling on this and for now I am going to leave this out, but let me share why - I want Skeleton to be fantastically simple and only provide the absolute basics. I am trying to avoid including multiple button styles or multiple styles for anything because that's not what Skeleton is about. It's not my intention for people to directly use Skeleton's styles for a site, but rather as a starting off point for a loose prototype or for the responsive grid. 

Hope this is clear, but would love to chat with you more about it if you would like. Hit me up at hi@getskeleton.com!

Thanks for your contribution and I hope your project is going well - would love to see the results if you get a chance to share those!

Cheers
Dave
