### ISSUE TITLE
one-third columns gets "uneven" at the end for me. Cant find what I do wrong

### ISSUE THREAD

**Issue by Lundholm** [dhg/Skeleton#163]
Hi

I have been pulling my hair out over this for a long time now, I cant find find what I am doing wrong.

I have a list that I would like to be stacked i a 3-column and it works nice up until almost the end when one ends up at the wrong side.

Does anyone have an idea what I am doining wrong?

![github](https://cloud.githubusercontent.com/assets/8488391/3963195/b0545e72-2777-11e4-8934-40b3a3a854b7.png)

http://www.klubblink.se/?c=bgcc

Best regards
Mikael

**Comment by deeve007** [comment]
It's the inherent weakness of using floats for column elements. Because the last item in the column is shorter than any other item in the row, the first item on the next row will position itself under that last column. Test it out by making that final column in row 3 a line or two higher.

I've been playing with using inline-blocks to solve this precise issue: https://github.com/deeve007/wpnaked-responsive-styled (very much a work in progress)

**Comment by dhg** [comment]
I'm really sorry I never got to this in a timely fashion originally. I left Skeleton in terrible disrepair for a couple years and without an active developer. I'm back at it though and committed to continuing development. I released v2.0 a week or so ago and am making my way through all the old issues and PRs.

The issue here was not wrapping a given row of items in a `.row`. That's how Skeleton (both in v1 and v2) clears a given set of columns with varying heights. Hope that helps and sorry about not getting to this sooner :(
