### ISSUE TITLE
Skeleton Less file

### ISSUE THREAD

**Issue by robeno** [dhg/Skeleton#183]
It would be really nice to have skeleton written also in [LESS](http://lesscss.org/)

**Comment by kemie** [comment]
Yes!

**Comment by luisrudge** [comment]
:+1:

**Comment by niallobrien** [comment]
I'm sure the same can be said for Sass, Stylus etc.

**Comment by luisrudge** [comment]
That's the real problem :D It's impossible to support every language :(

**Comment by niallobrien** [comment]
I'd be interested in porting this to other pre-processors if anyone else is on board?

**Comment by luisrudge** [comment]
That's the easy part. The hard part is to keep it up to date. It should be automated, really :(

**Comment by niallobrien** [comment]
I mean an independent project sharing the same ideals etc.

**Comment by luisrudge** [comment]
Maybe we can automate some stuff with this projects?

https://github.com/sickill/css2less
https://github.com/jpablobr/css2sass

**Comment by niallobrien** [comment]
I want a Stylus version. ;)

**Comment by luisrudge** [comment]
no problem :)
https://github.com/dciccale/css2stylus.js

**Comment by niallobrien** [comment]
Lol, yeah - already used that. It only goes so far.
Convert whatever you need so, however I don't think any of these belong in Skeleton as they all introduce a compilation step.

**Comment by luisrudge** [comment]
Yeah, I'm thinking about that too. It could be on a gulp file.. I don't know if it makes sense to have this all distributed on different repos..

**Comment by luisrudge** [comment]
Having a gulp file also would make the css cleaner, adding prefixes and whatever

**Comment by luisrudge** [comment]
But having in the same repo would make it hard to install via bower. Maybe different repos makes more sense.

**Comment by niallobrien** [comment]
Perhaps, but I'd recommend forking this project instead.

**Comment by luisrudge** [comment]
css2less was a nightmare. it doesn't do anything good :|

**Comment by kemie** [comment]
Haven't tried it, but heard good things about http://toki-woki.net/p/least/

**Comment by luisrudge** [comment]
@kemie I tried but:

> Warning! Known issues with @media queries and data URIs.

:(

**Comment by kemie** [comment]
OK, I might be able to give this a shot manually later in the week

**Comment by luisrudge** [comment]
@kemie I was going to do the less version. Do you wanna do that too? I can contribute to your repo if you want too.

**Comment by kemie** [comment]
I want to but not sure when I'll have the time so be my guest ;)

**Comment by stephenlacy** [comment]
In the case of modularity, what about splitting each interface group into it's own (sass, less, stylus, etc) file and compiling them with gulp?
I would be glad to help setup the gulp build process.

**Comment by deeve007** [comment]
Fork.

**Comment by nafoster** [comment]
Did a very simple conversion to Sass: https://github.com/nafoster/Skeleton

I want to add more variables and helpful mixins, but I figured it was a good start.

Edit: Just realized somebody did this already, but with variables and mixins. [Kudos to them!](https://github.com/dhg/Skeleton/pull/127)

**Comment by dmur** [comment]
I agree with @deeve007 and @niallobrien that the solution is to fork.  It seems like adding support for all of them could snowball quickly into something unmaintainable.  And I'm assuming the lack of Less/Sass/Stylus versions is intentional (and not because Dave hasn't considered it).  

I'm also not clear on what having a Less/Sass/Stylus version adds.  Is there some reason the Skeleton CSS can't be used alongside other Less/Sass/Stylus stylesheets?

**Comment by luisrudge** [comment]
@dmur mainly the use of variables and mixins.

**Comment by niallobrien** [comment]
Just fork or port guys. Please stop talking about doing something and just do it. Simples.
Personally, I think that a nestable grid should be a higher priority.

**Comment by niallobrien** [comment]
Though for multi-levels of grid nesting you'd need a preprocessor to calculate the % widths anyways.

**Comment by dhg** [comment]
Hey ya'll, 

Glad to see everyone in here :) So, I definitely considered using less/sass/stylus for the project, but realized, to me, part of the beauty of Skeleton is its simplicity and ease of understanding for first timers. That said, I don't want Skeleton to be limited by a commitment to newcomers to RWD. 

There are obviously huge benefits to have a preprocessor, but with it comes added complexity. Fwiw, I don't think Skeleton core will include a preprocessor version (at least for a while).

I honestly haven't done enough open source to feel confident in saying forking is absolutely the right choice, but it feels right to me. The hard part is maintaining it in conjunction with the main project. So here's what I propose – Skeleton is going to get some updates over the next few days (as with any release it had bugs). I would wait until the next point release comes out, but then go crazy with building less/sass/stylus versions. 

If anyone creates a fork of v2 and is committed to keeping it up to date, I'd be happy to point people seeking a preprocessor versions of Skeleton in their direction! Just let me know here or hi@getskeleton.com.

I'm closing for now since I'm pretty solid that this version of Skeleton won't have LESS support in the framework, but I am _very_ in favor of creating an "officialish" fork. Obviously a largely requested feature in the community. 

Aside: @niallobrien - I'm considering how it _might_ be possible to do a nested grid. No promises, but toying with the idea.

**Comment by stephenlacy** [comment]
:+1: 
I would gladly help anyone setup a gulp build task with whatever preprocessor they choose.

**Comment by niallobrien** [comment]
Awesome, thanks @dhg

**Comment by dhg** [comment]
@stevelacy :) Thanks for the offer to help out! 

I just released 2.0.1 which had a fix for a bad bug in the offsets for the grid...hope not too many people suffer from that. I'm hopeful there's nothing else major, so forking _might_ be safe now, but I think best way to know is wait a few more days and see if anything else crops up in issues.

**Comment by nafoster** [comment]
@dhg If you think my Sass conversion is good, feel free to spread it around. I'll be keeping it up to date with plans to keep it lightweight.

[Enjoy!](https://github.com/nafoster/Skeleton)
