### ISSUE TITLE
Poor Windows Font Stack Rendering

### ISSUE THREAD

**Issue by dhg** [dhg/Skeleton#20]
An unconfirmed issue was reported that the standard Skeleton font stack can render poorly in a Windows environment without Helvetica. Need to check and confirm, then make needed CSS alterations.

**Comment by tnorthcutt** [comment]
I'm running Windows 7, and don't have Helvetica or any variants installed. I get served Arial on http://www.getskeleton.com, and it looks fine to me. What's the theory behind that issue? Without Helvetica installed, everyone on Windows should be getting Arial, which should work great in most if not all cases.

**Comment by dhg** [comment]
Thanks for the note! I've heard this several times so am closing this issue. If there are future issues, will re-open :)

**Comment by johanbrook** [comment]
Tip: instead of the "regular" sans-serif font stack Mac designers use:

```
font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
```

.. try using this one:

```
font-family: sans-serif;
```

Visitors with Mac OS X will automatically get Helvetica, and Windows visitors will get Arial. Helvetica looks really shitty on Windows, but Arial doesn't, so it's sometimes actually better to serve different fonts for the platforms rather than having precise control.
