### ISSUE TITLE
Controlling the minimum width of divs

### ISSUE THREAD

**Issue by pglaz** [dhg/Skeleton#261]
Hey guys, apologies if this is a basic question. I've noticed that Skeleton got updated and wanted to update it on my site but I'm running into an issue.

If we take the sample page included in the Skeleton archive and replace the contents with this code:

```
<div class="container">
    <div class="row">
        <div class="four columns" style="border: 1px solid #000;">
        <h3>Sidebar</h3>
    </div>

    <div class="eight columns" style="border: 1px solid #000;">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mauris quam, hendrerit quis posuere eget, auctor cursus turpis. Proin venenatis tempus sagittis. Nam laoreet neque eu nulla auctor hendrerit. Proin at feugiat ante. Fusce eu felis vel sem placerat vehicula eu sit amet metus. Ut consectetur sagittis massa, non sagittis nunc semper sed. Proin magna est, semper egestas tincidunt ac, luctus vitae magna.</p>
    </div>
  </div>
```

How do I control the minimum width of divs so that I avoid the main text on the right being so cramped for example? In other words, can I somehow control when the header would jump to be on top of the main content area in this case?

![screen shot 2015-03-22 at 01 35 27](https://cloud.githubusercontent.com/assets/4352382/6767503/c9acf98c-d033-11e4-89b3-09bdba973348.png)

**Comment by Escendrix** [comment]
Howdy,

unfortunately I do not understand your question, but I can help you with your markup which should help some problems.

All of your columns that add up to 12 (e.g. 6 columns + 6 columns) should be placed in a single row.  You can have several rows if needed, but the columns inside cannot add up to more than 12. Right now you have one row div but only one column that is 4 in length, so your second column that is 8 in length needs to be in the same row to add up to 12. Your markup is incorrect because you didn't close your four columns div and you placed the eight columns div outside the row div. All column divs need to be inside a row div.

Your code should now look like this, but again this is just a starting point to steer you in the correct direction.

``` HTML
<div class="container">
    <div class="row">
        <div class="four columns" style="border: 1px solid #000;">
            <h3>Sidebar</h3>
        </div>
        <div class="eight columns" style="border: 1px solid #000;">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mauris quam, hendrerit quis posuere eget, auctor cursus turpis. Proin venenatis tempus sagittis. Nam laoreet neque eu nulla auctor hendrerit. Proin at feugiat ante. Fusce eu felis vel sem placerat vehicula eu sit amet metus. Ut consectetur sagittis massa, non sagittis nunc semper sed. Proin magna est, semper egestas tincidunt ac, luctus vitae magna.</p>
        </div>
    </div>
</div>
```

**Comment by pglaz** [comment]
Thanks a lot for your reply! :) I see now how I've screwed up my markup.

What I was asking about is that if I start to resize the browser window down, the sidebar will get really thin before it'll "jump" on top of the text div. In my actual website layout, the fact that sidebar gets so thin before it's moved on top of the text div makes things really ugly. So I wanted to know if there is a way for me to prevent the sidebar from being resized to less than _n_ pixels so that things do not appear so crammed.
