### ISSUE TITLE
Push and pull classes

### ISSUE THREAD

**Issue by hadley** [dhg/Skeleton#27]
It would be great to have push and pull classes a la http://960.gs/, so that you have more freedom to place important content closer to the start of the page. This would be particularly nice for small screens so you can control what comes first.

**Comment by dhg** [comment]
This would be awesome, but I can't think of a great way to do this and support the media-queries of Skeleton. What I am going to do is replace the ".offset-by-#" classes to be more like 960.gs push classes (using position: relative and left: value rather than the current padding Skeleton has). 

If you have some genius black magic answer to reordering the stacking within all the media-queries I would love to hear it, but until then I'm going to close this issue. 

Thanks for the great idea and contribution!
