### ISSUE TITLE
Height of columns is not same

### ISSUE THREAD

**Issue by fy0** [dhg/Skeleton#289]
I think it's a problem.

**Comment by benhinchley** [comment]
@fy0 the height of the column will change depending on the content that is in it

**Comment by fy0** [comment]
@benhinchley 
For example, I want to show items with title, desc and a button.
Buttons should be aligned at bottom.
But height of items is not same, so it's a trouble.

**Comment by benhinchley** [comment]
@fy0 can you provide your markup for that section, so that it is easier to investigate the issue?

**Comment by fy0** [comment]
@benhinchley  Of course. here:  http://rpgame.net/example/

**Comment by akhyarrh** [comment]
You need a `div` with additional style to wrap your content

**Comment by ePirat** [comment]
I would not consider this a bug, as the usual behavior is that they do not have equal height.
There are various techniques out there to make them the same height (or look like they have the same height), none of which is perfect, so I think that's a bit out of scope of this (simple) CSS Framework.

**Comment by itsdarrylnorris** [comment]
:+1: for what @ePirat  said. @fy0 this problem is quite difficult and the only framework that I have seen that fix this issue is UIkit. To see how they fixed it check [Match height of panels](http://getuikit.com/docs/grid.html) in their grid page.

This will add a lot complexity to the project out scope of this project. Shall we close this issue ?

**Comment by fy0** [comment]
@darol100   Thanks.
= = I forgot to close the issue.
