### ISSUE TITLE
Improvements to base.css

### ISSUE THREAD

**Issue by necolas** [dhg/Skeleton#4]
Hope some of these suggestions are helpful.
- Removing `font:inherit` will mean that useful defaults, like italic font style for `i` and bold font-weight for `b`, won't be stripped.
- HelveticaNeue font stack can look nasty on Windows.
- No need for `line-height:inherit` for `em`, `strong,` and `small`.
- Duplication of `font-weight:normal` on lines 65 and 67.
- No need for `font-weight:normal` on line 73.
- Buttons could do with styles to fix common browser bugs related to use of `input` and `button` elements. See [css3 github buttons](https://github.com/necolas/css3-github-buttons) for the fixes (inc `overflow:visible` property for IE).
- Consider switching clearfix code (also in layout.css) to [micro clearfix](http://nicolasgallagher.com/micro-clearfix-hack/)

**Comment by dhg** [comment]
Hey, 

Great stuff. I definitely jumped in and made the edits on the line-height pieces and the font-weight redundancies. I will be pushing out those edits later today. 

As for the HelveticaNeue font stack...I think it looks alright in Windows, but if you get your hands a Windows machine and have an example of the gross rendering, let me know - I'd love to see it. 

I'm pulling in your active state for the buttons - I agree...active states are awesome. 

Finally, as for the 'micro-clearfix' - since the grid is so key to Skeleton, I am going to use it on my local build and when I do my next large round of testing, I will get a chance to make sure it works across all platforms and devices. If it does...it's totally in. 

Thanks so much for the contribution and look forward to a micro-release later today with those fixes.

Cheers

**Comment by dhg** [comment]
Going to close this issue and make one explicitly for the suggestion of micro-clearfix
