### ISSUE TITLE
CSS LESS support

### ISSUE THREAD

**Issue by sampi** [dhg/Skeleton#42]
I would really like to see CSS LESS support(meaning almost a full rewrite =( ) for this project to make it easily modifyable/minifyable/etc.

Are there any plans for this?

**Comment by dhg** [comment]
Hey Daniel - 

In an effort to keep Skeleton as simple and accesible as possible I will not be creating the project in LESS. I myself love LESS and use it frequently for larger projects, but don't see it in the future of Skeleton. There is however the fantastic Bootstrap project (a much more robust front-end framework) which is entirely built on LESS. Going to close this issue down since it's not in the cards, but thank you so much for sharing!

Cheers

**Comment by jcutrell** [comment]
I'd be open to developing a LESS branch for this.
