### ISSUE TITLE
Apple Touch Icons

### ISSUE THREAD

**Issue by dhg** [dhg/Skeleton#8]
The Apple touch icons are being properly delivered on iPhone 4 retina and iPad, but for some reason the standard 57x57 for iPhone 3 isn't working. Instead, on iPhone 3, a scaled version of the 114x114 for the iPhone 4 is getting served. Need to figure out why and fix it :)

**Comment by connor** [comment]
Hmmm, I'm not sure. According to Apple's HIG (http://developer.apple.com/library/ios/#documentation/userexperience/conceptual/mobilehig/IconsImages/IconsImages.html), we need to provide both. I haven't looked too far into the issue yet. Have you found a solution yet, by chance?

**Comment by dhg** [comment]
Hey Connor, 

No. I've linked all three sizes per Apple's guidelines, but I did a test with different icons for each size and the iPhone 3 continued to get a scaled version of the retina 114x114 size. I will be playing with it more today to see if I can resolve it :)

Let me know if you figure anything out!

**Comment by ghost** [comment]
Btw you don't have to put these lines into HTML

Link — http://mathiasbynens.be/notes/touch-icons

**Comment by connor** [comment]
We need to do a few things:
- move all the images in `/images` to the root (since they're just favicons).
- remove all reference to the favicons in the HTML.
- rename `apple-touch-icon.png` to `apple-touch-icon-57x57.png`.
- create a `apple-touch-icon-144x144.png` that is 144px x  144px.
- possibly prepend each of these apple-touch-icon names with `-precomposed`, so they don't get the gloss over them?

@dhgamache I can do all of those except creating the 144x144 one, since I don't know what font sizes you're using for the others and the image won't scale well. I probably will end up doing those in a PR, then will let you make the 144x144 one.

**Comment by dhg** [comment]
Closing since I removed Apple Touch icons w/ version 2.0
