### ISSUE TITLE
nav tag & JQuery

### ISSUE THREAD

**Issue by Qmuniq8** [dhg/Skeleton#92]
When I add an accordian menu list in the nav section of the skeleton (to replace the given page scroll menu) my menu does not work properly.

It displays correctly but when clicked the menu glitches out on all the buttons.

Is there something funadamental I am overlooking or ignorant of?

Or is there a fix?

I am a novice web designer (self taught)... so please bare with me.

regards

Tony

**Comment by atomicpages** [comment]
That sounds like an issue with your javascript rather than skeleton. Do you have some code we can look at and/or a url? I recommend using jsfiddle.net to upload your code if you don't have a live demo of it.

Also, github might not be the correct place for this either. There are many forums out there such as digitalpoint, daniweb, and stackoverflow that can probably provide a faster answer than on here.

**Comment by Qmuniq8** [comment]
Thanks for getting back to me. I resolved the issue by including the jquery script in the same div. That seemed to solve the problem. See; 

http://www.qmuniq8.com/iBrowsetc/DRAFT_hdBrows_02.html

You will see I'm struggling with layout.

Just as a sides.... is it my system or does chrome struggle with so much css stuff going on. What with the css animated background my system seems to struggle.

**Comment by atomicpages** [comment]
It is probably a system issue. It would also depend on your browser settings and how your machine is setup i.e. RAM, CPU, VRAM, etc...
Just know that css animations are a feature of CSS3 and not all browsers support it.

**Comment by dhg** [comment]
Glad this got resolved, but seemed like it wasn't directly related to Skeleton. If there's any future related issues though, lemme know.
